//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySpaceAssessmentApplication.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_CalculationTable
    {
        public int taxID { get; set; }
        public string PostCode { get; set; }
        public string YearlySalary { get; set; }
        public string TaxTotal { get; set; }
        public Nullable<System.DateTime> transcationDate { get; set; }
    }
}
